<a href="https://colab.research.google.com/github/TottiPuc/clasificador/blob/master/pytorch_create_save.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch.optim as optim
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://github.com/TottiPuc/clasificador/raw/master/storepurchasedata_large.csv")

In [3]:
df.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [4]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.20, random_state=0)

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [7]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [8]:
Xtrain_.shape, Xtest_.shape, 

(torch.Size([1243, 2]), torch.Size([311, 2]))

In [17]:
Ytrain_ = torch.from_numpy(y_train)
Ytest_ = torch.from_numpy(y_test)

In [9]:
input_size=2
output_size=2
hidden_size=10

In [12]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = torch.nn.Linear(input_size,hidden_size)
    self.fc2 = torch.nn.Linear(hidden_size,hidden_size)
    self.fc3 = torch.nn.Linear(hidden_size,output_size)

  def forward(self,X):
    X=torch.relu((self.fc1(X)))
    X=torch.relu((self.fc2(X)))
    X=self.fc3(X)

    return F.log_softmax(X,dim=1)

In [13]:
model=Net()

In [15]:
optimizer = optim.Adam(model.parameters(),lr=0.01)
loss_fn = nn.NLLLoss()

In [16]:
epochs=100

In [18]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred, Ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch ', epoch, 'loss ', loss.item())

Epoch  0 loss  0.7929921746253967
Epoch  1 loss  0.7718665599822998
Epoch  2 loss  0.7520915269851685
Epoch  3 loss  0.7336083650588989
Epoch  4 loss  0.7157862782478333
Epoch  5 loss  0.6976087093353271
Epoch  6 loss  0.6783786416053772
Epoch  7 loss  0.6583902835845947
Epoch  8 loss  0.6366864442825317
Epoch  9 loss  0.6134529113769531
Epoch  10 loss  0.58921879529953
Epoch  11 loss  0.5642188787460327
Epoch  12 loss  0.5393548607826233
Epoch  13 loss  0.5152455568313599
Epoch  14 loss  0.49198710918426514
Epoch  15 loss  0.4701276421546936
Epoch  16 loss  0.450001984834671
Epoch  17 loss  0.43152061104774475
Epoch  18 loss  0.4143925607204437
Epoch  19 loss  0.39839088916778564
Epoch  20 loss  0.3835430145263672
Epoch  21 loss  0.3692310154438019
Epoch  22 loss  0.3549734354019165
Epoch  23 loss  0.3403892517089844
Epoch  24 loss  0.32546377182006836
Epoch  25 loss  0.3103197515010834
Epoch  26 loss  0.2953605651855469
Epoch  27 loss  0.2806088924407959
Epoch  28 loss  0.26632207632

In [19]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0815, -1.1154],
         [-0.4264,  0.7409],
         [-0.2924,  0.7135],
         [ 0.9104,  0.1365],
         [ 0.0743,  1.0009],
         [-0.6860, -0.8065],
         [ 0.5314,  0.5557],
         [-0.6197,  0.5012],
         [ 1.0743,  0.5210],
         [ 0.8745,  0.1090]], requires_grad=True), Parameter containing:
 tensor([-0.2454,  0.3423,  0.7516,  0.3724, -0.0149,  0.3195, -0.1410, -0.7008,
          0.5806,  0.3602], requires_grad=True), Parameter containing:
 tensor([[ 0.4895,  0.1116,  0.2095,  0.6211,  0.6193, -0.6795,  0.5043, -0.1263,
           0.7003,  0.4613],
         [-0.1014,  0.1715, -0.2225,  0.0269, -0.3676, -0.0916,  0.2205,  0.1889,
          -0.0608,  0.0989],
         [-0.0481,  0.6516,  0.4326,  0.5160,  0.1627, -0.3272, -0.0363, -0.7043,
           0.2667,  0.4842],
         [-0.6784,  0.7390,  0.3212,  0.2279,  0.6587, -0.4292,  0.6384, -0.0842,
           0.2615,  0.3579],
         [-0.0609, -0.0832, -0.4188,  0.1102, -

In [20]:
torch.from_numpy(sc.transform(np.array([[40,22000]]))).float()

tensor([[-0.1704, -1.5960]])

In [21]:
y_cust_20_40000 = model(torch.from_numpy(sc.transform(np.array([[40,22000]]))).float())
y_cust_20_40000

tensor([[-5.0172e-03, -5.2974e+00]], grad_fn=<LogSoftmaxBackward>)

In [22]:
_,predicted_20_40000 = torch.max(y_cust_20_40000,-1)
predicted_20_40000

tensor([0])

In [23]:
torch.save(model,'customer_buy.pt')

In [24]:
!ls

customer_buy.pt  sample_data


In [25]:
restored_model = torch.load('customer_buy.pt')

In [26]:
y_cust_20_40000 = restored_model(torch.from_numpy(sc.transform(np.array([[40,22000]]))).float())
y_cust_20_40000

tensor([[-5.0172e-03, -5.2974e+00]], grad_fn=<LogSoftmaxBackward>)

In [27]:
model.state_dict()

OrderedDict([('fc1.weight', tensor([[ 0.0815, -1.1154],
                      [-0.4264,  0.7409],
                      [-0.2924,  0.7135],
                      [ 0.9104,  0.1365],
                      [ 0.0743,  1.0009],
                      [-0.6860, -0.8065],
                      [ 0.5314,  0.5557],
                      [-0.6197,  0.5012],
                      [ 1.0743,  0.5210],
                      [ 0.8745,  0.1090]])),
             ('fc1.bias',
              tensor([-0.2454,  0.3423,  0.7516,  0.3724, -0.0149,  0.3195, -0.1410, -0.7008,
                       0.5806,  0.3602])),
             ('fc2.weight',
              tensor([[ 0.4895,  0.1116,  0.2095,  0.6211,  0.6193, -0.6795,  0.5043, -0.1263,
                        0.7003,  0.4613],
                      [-0.1014,  0.1715, -0.2225,  0.0269, -0.3676, -0.0916,  0.2205,  0.1889,
                       -0.0608,  0.0989],
                      [-0.0481,  0.6516,  0.4326,  0.5160,  0.1627, -0.3272, -0.0363, -0.7043,
   

In [28]:
torch.save(model.state_dict(),'customer_buy_state_dict')

In [29]:
!ls

customer_buy.pt  customer_buy_state_dict  sample_data


In [30]:
!zip -r customer_buy_state_dict.zip customer_buy_state_dict

  adding: customer_buy_state_dict (deflated 49%)


In [32]:
from google.colab import files

In [33]:
files.download('customer_buy_state_dict.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>